// <auto-generated />
using JohnCherry_10_1_TicTacToe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JohnCherry_10_1_TicTacToe.Migrations
{
    [DbContext(typeof(TicTacContext))]
    partial class TicTacContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JohnCherry_10_1_TicTacToe.Models.TicTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WhosTurn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("square9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoWon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicTacToe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WhosTurn = "X",
                            square1 = "",
                            square2 = "",
                            square3 = "",
                            square4 = "",
                            square5 = "",
                            square6 = "",
                            square7 = "",
                            square8 = "",
                            square9 = "",
                            whoWon = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
